---
output: 
  pdf_document:
    latex_engine: xelatex
geometry: a4paper,landscape,left=3cm,right=3cm,top=1.5cm,bottom=1cm
header-includes:
  - \usepackage{fontspec}
  - \setmainfont{Arial}
  - \usepackage{titlesec}
  - \titleformat{\section}[block]{\normalfont\Large\bfseries}{\thesection}{1em}{}
  - \titleformat{\subsection}[block]{\normalfont\large\bfseries}{\thesubsection}{1em}{}
  - \titleformat{\subsubsection}[block]{\normalfont\small\bfseries}{\thesubsubsection}{1em}{}
params:
  mapdata: NA
  data_selected: NA
  min_est: 0
  max_est: 800
  reverse: FALSE
  legendentitel: "-"
  kennwert: "Mittelwert"
  na_label: ""
  quelle: ""
  woerterbuch: ""
  language: "de"
---
\pagenumbering{gobble}

```{r setup, include=FALSE}
library(ggplot2)
library(sf)
library(dplyr)
library(gridExtra)
library(grid)
library(viridis)
library(BTShinyApp)
```

```{r translation strings, echo = FALSE}
str_bundesland <- "Bundesland"
str_deutschland <- "Deutschland"
if(params$language == "en"){
  str_bundesland <- recode(str_bundesland, !!! params$woerterbuch)
  str_deutschland <- recode(str_deutschland, !!! params$woerterbuch)
}
```

```{r echo = FALSE}
data_selected <- params$data_selected
deutschlandwert <- unname(unlist(data_selected[data_selected$Bundesland == "total", "est_print"]))

data <- left_join(x = params$mapdata,
                   y = params$data_selected,
                   by = "Bundesland")
```

```{r echo=FALSE}
# Titel generieren

titel <- paste0(
  "IQB Bildungstrend, ",
  unique(na.omit(data$cycle)),
  ", ",
  unique(na.omit(data$year))
)

untertitel <- paste0(
  "Kompetenzbereich ",
  unique(na.omit(data$fachKb)), 
  ", ", 
  gsub("alle", "alle Schüler:innen", unique(na.omit(data$targetPop)))
)
```


```{r echo=FALSE, results='asis'}
# Titel anzeigen
cat(paste0(
  "# ", titel, "\n\n",
  "## ", untertitel, "\n\n"
))
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
# Karte plotten

karte <- ggplot(data) +
  geom_sf(aes(
    fill = est_delimited),
  color = "black") +
  theme_void() +
  scale_fill_viridis_c(
    limits = c(params$min_est, params$max_est),
    direction = ifelse(params$reverse,-1, 1), # hier sind große Zahlen schlecht
    name = params$legendentitel,
    guide = guide_colorbar(reverse = params$reverse)
  ) +
  theme(
    text = element_text(family = "ArialMT")  # Schriftart für Text
  )

karte_grob <- ggplotGrob(karte)
```


```{r echo=FALSE, warning=FALSE, message=FALSE}

# Datensatz mit relevanten Spalten erstellen
table_data <- sf::st_drop_geometry(data)[, c("Bundesland", "est_print")]

table_data[is.na(table_data$est_print),"est_print"] <- params$na_label
colnames(table_data) <- c(str_bundesland, params$legendentitel)

# Deutschlandwert wieder hinzufügen
last_row <- nrow(table_data) + 1
table_data[last_row,1] <- str_deutschland
table_data[last_row,2] <- deutschlandwert

tabelle <- gridExtra::tableGrob(
  table_data,
  rows = NULL,
  theme = gridExtra::ttheme_default(
    core = list(
      fg_params = list(cex = 0.8, fontfamily = "ArialMT")  # Schriftart für Tabellenzellen
    ),
    colhead = list(
      fg_params = list(cex = 0.9, fontfamily = "ArialMT")  # Schriftart für Kopfzeilen
    )
  )
)

```

```{r echo =FALSE, fig.height = 5.6, fig.width = 10}

# Neues Grid-Layout erstellen
grid.newpage()

# Layout definieren
layout <- grid.layout(nrow = 1, ncol = 2, widths = c(3, 2.5))
pushViewport(viewport(layout = layout))

# Karte in erster Spalte
pushViewport(viewport(layout.pos.row = 1, layout.pos.col = 1))
grid.draw(karte_grob)  # Zeichne Karte
popViewport()

# Tabelle in zweiter Spalte
pushViewport(viewport(layout.pos.row = 1, layout.pos.col = 2))
grid.draw(tabelle)  # Zeichne Tabelle
popViewport()

popViewport()  # Gesamtes Layout verlassen
```

\noindent\rule{3cm}{0.4pt}
**Die Daten sowie weitere Informationen sind dem entsprechenden Berichtsband zu entnehmen:**   

```{r echo=FALSE, results='asis'}
# Quellenangabe
cat(params$quelle)
```
