image: docker:23.0

variables:
  DOCKER_TLS_CERTDIR: ""

services:
  - name: docker:23.0-dind
    command: [ "--mtu=1442" ]

build:
  stage: build
  rules:
    - if: "$CI_COMMIT_TAG"  # Run only if a tag is present
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  script:
    - docker build -t scm.cms.hu-berlin.de:4567/iqb/homepage-shiny:$CI_COMMIT_TAG .
    - docker push scm.cms.hu-berlin.de:4567/iqb/homepage-shiny:$CI_COMMIT_TAG